
name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up OpenCV
      uses: EJRMdlRR/setup-opencv-action@v2
      with:
        opencv-version: '4.5.4'
        GENERATE_PKGCONFIG: ON
  
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: |
        cd ./detection
        go build -v

    - name: Test
      run: |
        cd ./detection
        go test -v
