
name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./detection

    - name: Test
      run: go test -v ./detection
 # main:
 #   runs-on: ubuntu-latest
 #   name: Example
 #   steps:
 #   - name: Checkout
 #     uses: actions/checkout@v1
 # 
 #   - name: Generate GoDoc
 #     uses: ktr0731/godoc-action@v0.1.0
 #     env:
 #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
